In [3]:
import numpy as np
a = np.array([0, 1, 2])
print(type(a))
print(a.shape)
print(a[0])
print(a[1])
print(a[2])
a[0] = 5
print(a)

<class 'numpy.ndarray'>
(3,)
0
1
2
[5 1 2]


In [5]:
import numpy as np
b = np.array([[0,1,2],[3,4,5]])
print(b.shape)
print(b)
print(b[0, 0], b[0, 1], b[1, 0])

(2, 3)
[[0 1 2]
 [3 4 5]]
0 1 3


In [7]:
import numpy as np
a = np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [11]:
import numpy as np
b = np.ones((2,2))
print(b)

[[1. 1.]
 [1. 1.]]


In [13]:
import numpy as np
c = np.full((3,3), 7)
print(c)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [17]:
import numpy as np
d = np.random.random((3,3))
print(d)

[[0.12031538 0.93756044 0.43946912]
 [0.81161376 0.46518242 0.67062762]
 [0.60727118 0.7706147  0.78567452]]


In [19]:
import numpy as np
e = np.eye(3)
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [21]:
import numpy as np
f = np.array([2, 3, 1, 0])
print(f)

[2 3 1 0]


In [23]:
import numpy as np
g = np.arange(20)
print(g)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [25]:
import numpy as np
h = np.array([[0, 1,2.0],[0,0,0],(1+1j,3.,2.)])
print(h)

[[0.+0.j 1.+0.j 2.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]
 [1.+1.j 3.+0.j 2.+0.j]]


In [29]:
import numpy as np
i = np.arange(1, 8, dtype=float)
print(i)


[1. 2. 3. 4. 5. 6. 7.]
